# Generated by Django 2.2.28 on 2022-05-27 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('creationDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
