# Generated by Django 2.2.28 on 2022-05-28 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0002_auto_20220527_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docs',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
