# Generated by Django 3.2.15 on 2022-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0003_auto_20220528_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
