# Generated by Django 2.2.28 on 2022-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
