# Generated by Django 2.2.28 on 2022-06-16 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('names', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('expiration_date', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('modelType', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creationDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.PassportModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
