# Generated by Django 2.2.28 on 2022-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportmodel',
            name='ref',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
