# Generated by Django 2.2.28 on 2022-06-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_passportmodel_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('emise_date', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=200, null=True)),
                ('cle_de_securite', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vitale_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.VitaleModel'),
        ),
    ]
